#  FOR CHANGING LINE WE USE TRIPLE SINGLE COTATION
# USE BACK SLASH IF YOU WANT TO USE '' IN OUTPUT USE /

# SINGLE LINE COMMENT USE(#)
# FOR MULTIPLNE LINE COMMENT WE USE (""")

a = "hello"
# a is variable(it is use to represent anything )

name = input("Enter Your Nmae")
print(name)
# input is use in py to give input same as a scanner in java 
age = int(input("Enter your age"))
# command for data_type input

# TYPCASTING = CONVERTING ONE DATATYPE INTO OTHER 
# 1 IMPLICIT TYPECASTING
# 2 EXPLICIT TYPECASTING


#identity operator is & is not  

#Membership Operators
# is  & is not



Marks =  float(input("Enter your Marks:- "))
if Marks >= 90:
    print("top the class")